### PR TITLE
Fixed problems with React and Jest incorrect errors

### PR DESCRIPTION
**Pull request by DanielHoffmann**

### CODE REVIEW

**Comment by ollhar** [comment]
@DanielHoffmann changelog has not been updated with description and no clear problem description.

**Comment by simonauner** [comment]
@DanielHoffmann could you please provide some information about the issue you are solving with this? Some examples of what brakes with the current setup?

**Comment by DanielHoffmann** [comment]
@ollhar @simonauner 

So basically the jest configuration was completely broken because it was pointing to the wrong eslint plugin (was pointing to "react" instead of "jest"), making all the Jest rules not be available

The React configuration I added the rule `"react/jsx-uses-react" : 2` (https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-react.md) which makes eslint NOT throw an error when you import React but don't use it directly. This is necessary in files where you use JSX, but don't use `React.Component` otherwise it would throw a `React is defined, but not used (no-undef)` error in those files.

I also updated changelog and added instructions for setting linting up in React/Jest projects in theREADME as well

**Comment by simonauner** [comment]
Great, thanks for the explanation @DanielHoffmann !

**Pull request merged**
